<?php
// This migration adds a total_yearly_cost table to store the total yearly cost of all subscriptions over time
// This migration adds a start_date column to the subscriptions table to store the start date of the subscription
// This migration adds a auto_renew column to the subscriptions table to store if the subscription renews automatically or needs manual renewal

$tableQuery = $db->query("SELECT table_name AS name FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'total_yearly_cost'");
$tableRequired = $tableQuery->fetchArray(PDO::FETCH_ASSOC) === false;

if ($tableRequired) {
    $db->exec('CREATE TABLE total_yearly_cost (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        date INTEGER NOT NULL,
        cost REAL NOT NULL,
        currency TEXT NOT NULL
    )');
}

$columnQuery = $db->query("SELECT column_name AS name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'total_yearly_cost'");
$columns = [];
while ($column = $columnQuery->fetchArray(PDO::FETCH_ASSOC)) {
    $columns[] = $column['name'];
}

if (!in_array('start_date', $columns)) {
    $db->exec('ALTER TABLE subscriptions ADD COLUMN start_date DATE DEFAULT NULL');
}

if (!in_array('auto_renew', $columns)) {
    $db->exec('ALTER TABLE subscriptions ADD COLUMN auto_renew INTEGER DEFAULT 1');
}

?>