<?php
// This migration adds a "password_login_disabled" column to the "oauth_settings" table
// This migration also adds a "ai_settings" table to store AI settings.
// This migration also adds a "ai_recommendations" table to store AI recommendations.

$columnQuery = $db->query("SELECT column_name AS name FROM information_schema.columns WHERE table_schema = current_schema() AND table_name = 'oauth_settings' AND column_name = 'password_login_disabled'");
$columnRequired = $columnQuery->fetchArray(PDO::FETCH_ASSOC) === false;

if ($columnRequired) {
    $db->exec("ALTER TABLE oauth_settings ADD COLUMN password_login_disabled INTEGER DEFAULT 0");
} 

// Check if ai_settings table exists, if not, create it
$tableQuery = $db->query("SELECT table_name AS name FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'ai_recommendations'");
$tableExists = $tableQuery->fetchArray(PDO::FETCH_ASSOC);

if ($tableExists === false) {
    $db->exec("
        CREATE TABLE ai_settings (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            type TEXT NOT NULL,
            enabled INTEGER NOT NULL DEFAULT 0,
            api_key TEXT,
            model TEXT NOT NULL,
            url TEXT,
            run_schedule TEXT NOT NULL DEFAULT 'manual',
            last_successful_run TIMESTAMP,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    ");
}

// Check if ai_recommendations table exists, if not, create it
$tableQuery = $db->query("SELECT table_name AS name FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'ai_recommendations'");
$tableExists = $tableQuery->fetchArray(PDO::FETCH_ASSOC);

if ($tableExists === false) {
    $db->exec("
        CREATE TABLE ai_recommendations (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            type TEXT NOT NULL,
            title TEXT NOT NULL,
            description TEXT NOT NULL,
            savings TEXT NOT NULL DEFAULT '',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    ");
}