<?php
// This migration adds the "google_search" table, holding the optional
// SerpAPI key used to add Google image results to the subscription logo search.

$tableQuery = $db->query("SELECT table_name AS name FROM information_schema.tables WHERE table_schema = current_schema() AND table_name = 'google_search'");
$tableRequired = $tableQuery->fetchArray(PDO::FETCH_ASSOC) === false;

if ($tableRequired) {
    $db->exec("CREATE TABLE google_search (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        api_key TEXT NOT NULL DEFAULT ''
    )");
}
