<?php

require_once __DIR__ . '/../../includes/database.php';

try {
    $db = new WallosDatabase();
} catch (Throwable $exception) {
    fwrite(STDERR, 'Database initialization failed: ' . $exception->getMessage() . PHP_EOL);
    exit(1);
}

$tables = [
    'CREATE TABLE IF NOT EXISTS currencies (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, symbol TEXT NOT NULL, code TEXT NOT NULL, rate REAL NOT NULL)',
    'CREATE TABLE IF NOT EXISTS "user" (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT NOT NULL, email TEXT NOT NULL, password TEXT NOT NULL, main_currency INTEGER NOT NULL, avatar TEXT, FOREIGN KEY (main_currency) REFERENCES currencies(id))',
    'CREATE TABLE IF NOT EXISTS payment_methods (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, icon TEXT)',
    'CREATE TABLE IF NOT EXISTS categories (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL)',
    'CREATE TABLE IF NOT EXISTS household (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL)',
    'CREATE TABLE IF NOT EXISTS cycles (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, days INTEGER NOT NULL, name TEXT NOT NULL)',
    'CREATE TABLE IF NOT EXISTS frequencies (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name INTEGER NOT NULL)',
    'CREATE TABLE IF NOT EXISTS subscriptions (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, logo TEXT, price REAL NOT NULL, currency_id INTEGER, next_payment DATE, cycle INTEGER, frequency INTEGER, notes TEXT, payment_method_id INTEGER, payer_user_id INTEGER, category_id INTEGER, notify INTEGER DEFAULT 0, FOREIGN KEY (currency_id) REFERENCES currencies(id), FOREIGN KEY (cycle) REFERENCES cycles(id), FOREIGN KEY (frequency) REFERENCES frequencies(id), FOREIGN KEY (payment_method_id) REFERENCES payment_methods(id), FOREIGN KEY (payer_user_id) REFERENCES household(id), FOREIGN KEY (category_id) REFERENCES categories(id))',
    'CREATE TABLE IF NOT EXISTS login_tokens (user_id INTEGER NOT NULL, token TEXT NOT NULL, timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE)',
    'CREATE TABLE IF NOT EXISTS fixer (api_key TEXT NOT NULL)',
    'CREATE TABLE IF NOT EXISTS last_exchange_update (date DATE NOT NULL)',
    'CREATE TABLE IF NOT EXISTS last_update_next_payment_date (date DATE NOT NULL)',
    'CREATE TABLE IF NOT EXISTS notifications (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, enabled INTEGER DEFAULT 0, days INTEGER, smtp_address VARCHAR(255), smtp_port INTEGER, smtp_username VARCHAR(255), smtp_password VARCHAR(255))',
];

foreach ($tables as $table) {
    $db->exec($table);
}

$db->exec("INSERT INTO categories (id, name) VALUES
    (1, 'No category'), (2, 'Entertainment'), (3, 'Music'), (4, 'Utilities'),
    (5, 'Food & Beverages'), (6, 'Health & Wellbeing'), (7, 'Productivity'),
    (8, 'Banking'), (9, 'Transport'), (10, 'Education'), (11, 'Insurance'),
    (12, 'Gaming'), (13, 'News & Magazines'), (14, 'Software'), (15, 'Technology'),
    (16, 'Cloud Services'), (17, 'Charity & Donations') ON CONFLICT (id) DO NOTHING");

$db->exec("INSERT INTO cycles (id, days, name) VALUES
    (1, 1, 'Daily'), (2, 7, 'Weekly'), (3, 30, 'Monthly'),
    (4, 365, 'Yearly'), (5, 0, 'One-time') ON CONFLICT (id) DO NOTHING");

$frequencyValues = implode(', ', array_map(static fn(int $value): string => "($value, $value)", range(1, 31)));
$db->exec("INSERT INTO frequencies (id, name) VALUES $frequencyValues ON CONFLICT (id) DO NOTHING");

$currencies = [
    ['Euro', '€', 'EUR'], ['US Dollar', '$', 'USD'], ['Japanese Yen', '¥', 'JPY'],
    ['Bulgarian Lev', 'лв', 'BGN'], ['Czech Republic Koruna', 'Kč', 'CZK'], ['Danish Krone', 'kr', 'DKK'],
    ['British Pound Sterling', '£', 'GBP'], ['Hungarian Forint', 'Ft', 'HUF'], ['Polish Zloty', 'zł', 'PLN'],
    ['Romanian Leu', 'lei', 'RON'], ['Swedish Krona', 'kr', 'SEK'], ['Swiss Franc', 'Fr', 'CHF'],
    ['Icelandic Króna', 'kr', 'ISK'], ['Norwegian Krone', 'kr', 'NOK'], ['Russian Ruble', '₽', 'RUB'],
    ['Turkish Lira', '₺', 'TRY'], ['Australian Dollar', '$', 'AUD'], ['Brazilian Real', 'R$', 'BRL'],
    ['Canadian Dollar', '$', 'CAD'], ['Chinese Yuan', '¥', 'CNY'], ['Hong Kong Dollar', 'HK$', 'HKD'],
    ['Indonesian Rupiah', 'Rp', 'IDR'], ['Israeli New Sheqel', '₪', 'ILS'], ['Indian Rupee', '₹', 'INR'],
    ['South Korean Won', '₩', 'KRW'], ['Mexican Peso', 'Mex$', 'MXN'], ['Malaysian Ringgit', 'RM', 'MYR'],
    ['New Zealand Dollar', 'NZ$', 'NZD'], ['Philippine Peso', '₱', 'PHP'], ['Singapore Dollar', 'S$', 'SGD'],
    ['Thai Baht', '฿', 'THB'], ['South African Rand', 'R', 'ZAR'], ['Ukrainian Hryvnia', '₴', 'UAH'],
    ['New Taiwan Dollar', 'NT$', 'TWD'],
];
$currencyValues = implode(', ', array_map(static fn(array $currency): string => sprintf("('%s', '%s', '%s', 1)", ...$currency), $currencies));
$db->exec("INSERT INTO currencies (name, symbol, code, rate) SELECT * FROM (VALUES $currencyValues) AS seed(name, symbol, code, rate) WHERE NOT EXISTS (SELECT 1 FROM currencies)");

$paymentMethods = [
    'PayPal', 'Credit Card', 'Bank Transfer', 'Direct Debit', 'Money', 'Google Pay', 'Samsung Pay',
    'Apple Pay', 'Crypto', 'Klarna', 'Amazon Pay', 'SEPA', 'Skrill', 'Sofort', 'Stripe', 'Affirm',
    'AliPay', 'Elo', 'Facebook Pay', 'GiroPay', 'iDeal', 'Union Pay', 'Interac', 'WeChat', 'Paysafe',
    'Poli', 'Qiwi', 'ShopPay', 'Venmo', 'VeriFone', 'WebMoney',
];
$paymentValues = implode(', ', array_map(static fn(string $name, int $index): string => sprintf("(%d, '%s', '%s.png')", $index + 1, $name, strtolower(str_replace(' ', '', $name))), $paymentMethods, array_keys($paymentMethods)));
$db->exec("INSERT INTO payment_methods (id, name, icon) SELECT * FROM (VALUES $paymentValues) AS seed(id, name, icon) WHERE NOT EXISTS (SELECT 1 FROM payment_methods)");

echo "PostgreSQL schema initialized.\n";

?>
